Controllers/ActorsController.cs
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Actors/Create
        public  IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        //Get: Actors/Details/Id
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        //Get: Actors/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }

        //Get: Actors/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/MoviesController.cs
using AspNetCoreMultilingual.Languages;
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using System.Data;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        private readonly IStringLocalizer<Lang> _stringLocalizer;

        public MoviesController(IStringLocalizer<Lang> stringLocalizer, IMoviesService service)
        {
            _stringLocalizer = stringLocalizer;
            _service = service;
        }
        [AllowAnonymous]
        public IActionResult SetAppLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
        [AllowAnonymous]
        public IActionResult SetCulture(string id = "en")
        {
            string culture = id;
            Response.Cookies.Append(
               CookieRequestCultureProvider.DefaultCookieName,
               CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
               new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
           );

            ViewData["Message"] = "Culture set to " + culture;

            return View("Privacy");
        }
   
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            return View(allMovies);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);

            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allMovies);
        }

        //GET: Movies/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id);
            return View(movieDetail);
        }

        //GET: Movies/Create
        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }


        //GET: Movies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };

            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (id != movie.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/SelectCulture.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> locOptions

 @{
    var currentRequestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = locOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var responseUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request the culture provider:"] @currentRequestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Movies" 
          asp-action="SetAppLanguage" asp-route-returnUrl="@responseUrl"
          method="post" class="form-horizontal" role="form">
        <i class="fa fa-globe" style="font-size:36px"></i>
        <select name="culture" style="background:#474747;border-style: none;border-radius: 100px; width:15px; margin-right:30px;"
                onchange="this.form.submit();"
                asp-for="@currentRequestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
            
        </select>
    </form>
</div>

Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Views/Shared/_Head.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>

Views/Shared/_Header.cshtml
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        }

                    </ul>

                    <form class="d-inline-flex my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>

Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn  my-2 my-sm-0" asp-controller="Account" asp-action="Login" style="    font-size: 0.9375rem; color: white; border-style: none;border-radius: 50px;">
         Giriş yap
    </a>
    <span style="padding: 2px;"></span>

    <a class="btn  my-2 my-sm-0" asp-controller="Account" asp-action="Register" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
         Kayıt ol
    </a>
}
else
{

    @*User profile section*@
    <div class="" style="flex-direction: row;">
        
       
         
            <a class="btn  my-2 my-sm-0" style=" font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">Hello @UserManager.GetUserName(User)</a> 
           
       
                <a class="btn  my-2 my-sm-0" asp-controller="Orders" asp-action="Index" style=" font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
                    Biletler
                </a>
       

          
       
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
            <i class="bi bi-box-arrow-in-right"></i> Çıkış yap
        </button>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<html lang="en">
<head>
    
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        
            <div class="container-fluid" style=" display: flex;
    align-items:center ;
padding:15px;
    justify-content: space-between;
    background:#474747">
               <img src="https://kdaidggt0f3v.merlincdn.net/dist/assets/img/logo.svg" alt="biletinial" href="#" class="logo">
                <span style="padding: 5px;"></span>
                <div class="navbar-collapse  d-sm-inline-flex ">
                    <ul class="navbar-nav flex-grow-1" style="flex-direction: row;">
                        <li class="nav-item">
                            <a class="btn  my-2 my-sm-0" asp-area="" asp-controller="Movies" asp-action="Index"  style=" font-size: 20px; color: white;border-style: none;border-radius: 50px;">@Localizer["Filmler"]</a>
                           
                        </li>
                         <span style="padding: 5px;"></span>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li>
                            <a class="btn  my-2 my-sm-0" asp-controller="Cinemas" asp-action="Index" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;"><i class="bi bi-camera-reels" style=" font-size: 20px; border-style: none;border-radius: 50px;"></i> @Localizer["Sinemalar"]</a>
                            </li>
                            <li>
                            <a class="btn  my-2 my-sm-0" asp-controller="Producers" asp-action="Index" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;"><i class="bi bi-headset" style=" font-size: 20px; border-style: none;border-radius: 50px;"></i> @Localizer["Yapımcılar"]</a>
                            </li>
                            <li>
                                    <a class="btn  my-2 my-sm-0" asp-controller="Actors" asp-action="Index" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;"><i class="bi bi-person-square" style=" font-size: 20px; border-style: none;border-radius: 50px;"></i> @Localizer["Aktörler"]</a>
                            </li>
                             <li>
                                <a class="btn  my-2 my-sm-0" asp-controller="Account" asp-action="Users" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
                                    <i class="bi bi-people" style=" font-size: 20px; border-style: none;border-radius: 50px;"></i> @Localizer["Kullanıcılar"]
                                </a>
                            </li>            
                            
                        }
                    <div class="">
                            @await Html.PartialAsync("SelectCulture")
                        </div>
                         <span style="margin-left: 40px;"></span>
                        <form class="d-inline-flex my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" >
                        <input name="searchString" type="text" class="form-control" placeholder=@Localizer["Ara"] aria-label="Recipient's username" aria-describedby="button-addon2" style="background-color:#F8E71C;border-style: none;border-radius: 50px;">
                         <span style="padding: 5px;"></span>
                        <button class="" style="background-color:#F8E71C;border-style: none;border-radius: 100px;" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <li>
                       
                    </li>
                    </ul>

                    

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                @using Microsoft.AspNetCore.Identity;
                @inject UserManager<ApplicationUser> UserManager;
                @using Microsoft.AspNetCore.Mvc.Localization
                @inject IViewLocalizer Localizer
                @if (!User.Identity.IsAuthenticated)
                {
                    <a class="btn  my-2 my-sm-0" asp-controller="Account" asp-action="Login" style="    font-size: 0.9375rem; color: white; border-style: none;border-radius: 50px;">
                        @Localizer["Giriş"]
                    </a>
                    <span style="padding: 2px;"></span>

                    <a class="btn  my-2 my-sm-0" asp-controller="Account" asp-action="Register" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
                        @Localizer["Kayıt Ol"]
                    </a>
                }
                else
                {

                    @*User profile section*@
                    <div class="" style="flex-direction: row;">



                        <a class="btn  my-2 my-sm-0" style=" font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">Hello @UserManager.GetUserName(User)</a>


                        <a class="btn  my-2 my-sm-0" asp-controller="Orders" asp-action="Index" style=" font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
                            @Localizer["Biletler"]
                        </a>




                    </div>
                    <span style="padding: 5px;"></span>

                    <form asp-controller="Account" asp-action="Logout">
                        <button class="btn btn-outline-danger my-2 my-sm-0" style="    font-size: 0.9375rem; color: white;border-style: none;border-radius: 50px;">
                            <i class="bi bi-box-arrow-in-right"></i> @Localizer["Çıkış"]
                        </button>
                    </form>
                }

                </div>
            </div>
            <span style="padding:10px;"></span>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted position-relative">
        <div class="container">
            &copy; 2021 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/css/site.css" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/css/site.css" ></script>